const state = {
  timeframes: [],
  strategies: [],
  selectedTimeframes: [],
  selectedStrategies: [],
  filters: [
    { field: "win_rate", op: ">=", value: "65" },
    { field: "profit_factor", op: ">=", value: "1.2" },
  ],
  filterFields: [],
  filterFieldGroups: {},
  operators: [],
  mode: "normal",
  columns: [],
  rows: [],
  columnVisibility: {},
  fontSize: 13,
  searchText: "",
  loading: false,
  sortCol: null,
  sortDir: "asc",
  rowSelect: {},
  ratings: {},
  currentRunId: null,
  currentRunMeta: null,
  savedRuns: [],
  rowNotes: {},
  dirty: false,
  loadedFromSave: false,
  lastRunPayload: null,
  lastTiming: null,
  runningStartTime: null,
  strategyParamSchemas: {},
  gridParamSchema: {},
  strategySettings: {},
  activeStrategy: null,
  gridSettings: {
    profile: "normal",
    sl_values: "",
    tp_values: "",
    max_holds: "",
  },
  densitySettings: {
    min_trades_per_day: 0.33,
    min_test_trades_per_day: 0.33,
  },
  executionSettings: {
    entry_next_open: false,
    use_spread_slippage: false,
    spread_pct: 0,
    slippage_pct: 0,
    show_rr_metrics: false,
    compute_ambiguity_metrics: false,
  },
  riskSettings: {
    use_position_sizing: false,
    risk_per_trade_pct: 1.0,
    use_leverage: false,
    leverage: 1,
    use_liquidation: false,
    maintenance_margin_pct: 0.5,
  },
  lastRunConfigSnapshot: null,
  runningConfigSnapshot: null,
};

function setState(updates) {
  Object.assign(state, updates);
}
